package goodboy.other;

import java.util.HashMap;

public class Metadata {
    public static HashMap<Integer, String> licensee = new HashMap<>();
    public static HashMap<Integer, String> cartridgeType = new HashMap<>();
    public static HashMap<Integer, String> romSize = new HashMap<>();
    public static HashMap<Integer, String> ramSize = new HashMap<>();

    static {
        licensee.put(0x00, "none");
        licensee.put(0x01, "nintendo");
        licensee.put(0x08, "capcom");
        licensee.put(0x09, "hot-b");
        licensee.put(0x0A, "jaleco");
        licensee.put(0x0B, "coconuts");
        licensee.put(0x0C, "elite systems");
        licensee.put(0x13, "electronic arts");
        licensee.put(0x18, "hudsonsoft");
        licensee.put(0x19, "itc entertainment");
        licensee.put(0x1A, "yanoman");
        licensee.put(0x1D, "clary");
        licensee.put(0x1F, "virgin");
        licensee.put(0x20, "KSS");
        licensee.put(0x24, "pcm complete");
        licensee.put(0x25, "san-x");
        licensee.put(0x28, "kotobuki systems");
        licensee.put(0x29, "seta");
        licensee.put(0x30, "infogrames");
        licensee.put(0x31, "nintendo");
        licensee.put(0x32, "bandai");
        licensee.put(0x34, "konami");
        licensee.put(0x35, "hector");
        licensee.put(0x38, "Capcom");
        licensee.put(0x39, "Banpresto");
        licensee.put(0x3C, "*entertainment i");
        licensee.put(0x3E, "gremlin");
        licensee.put(0x41, "Ubisoft");
        licensee.put(0x42, "Atlus");
        licensee.put(0x44, "Malibu");
        licensee.put(0x46, "angel");
        licensee.put(0x47, "spectrum holoby");
        licensee.put(0x49, "irem");
        licensee.put(0x4A, "virgin");
        licensee.put(0x4D, "malibu");
        licensee.put(0x4F, "u.s. gold");
        licensee.put(0x50, "absolute");
        licensee.put(0x51, "acclaim");
        licensee.put(0x52, "activision");
        licensee.put(0x53, "american sammy");
        licensee.put(0x54, "gametek");
        licensee.put(0x55, "park place");
        licensee.put(0x56, "ljn");
        licensee.put(0x57, "matchbox");
        licensee.put(0x59, "milton bradley");
        licensee.put(0x5A, "mindscape");
        licensee.put(0x5B, "romstar");
        licensee.put(0x5C, "naxat soft");
        licensee.put(0x5D, "tradewest");
        licensee.put(0x60, "titus");
        licensee.put(0x61, "virgin");
        licensee.put(0x67, "ocean");
        licensee.put(0x69, "electronic arts");
        licensee.put(0x6E, "elite systems");
        licensee.put(0x6F, "electro brain");
        licensee.put(0x70, "Infogrammes");
        licensee.put(0x71, "Interplay");
        licensee.put(0x72, "broderbund");
        licensee.put(0x73, "sculptered soft");
        licensee.put(0x75, "the sales curve");
        licensee.put(0x78, "t*hq");
        licensee.put(0x79, "accolade");
        licensee.put(0x7A, "triffix entertainment");
        licensee.put(0x7C, "microprose");
        licensee.put(0x7F, "kemco");
        licensee.put(0x80, "misawa entertainment");
        licensee.put(0x83, "lozc");
        licensee.put(0x86, "tokuma shoten intermedia");
        licensee.put(0x8B, "bullet-proof software");
        licensee.put(0x8C, "vic tokai");
        licensee.put(0x8E, "ape");
        licensee.put(0x8F, "i'max");
        licensee.put(0x91, "chun soft");
        licensee.put(0x92, "video system");
        licensee.put(0x93, "tsuburava");
        licensee.put(0x95, "varie");
        licensee.put(0x96, "yonezawa/s'pal");
        licensee.put(0x97, "kaneko");
        licensee.put(0x99, "arc");
        licensee.put(0x9A, "nihon bussan");
        licensee.put(0x9B, "Tecmo");
        licensee.put(0x9C, "imagineer");
        licensee.put(0x9D, "Banpresto");
        licensee.put(0x9F, "nova");
        licensee.put(0xA1, "Hori electric");
        licensee.put(0xA2, "Bandai");
        licensee.put(0xA4, "Konami");
        licensee.put(0xA6, "kawada");
        licensee.put(0xA7, "takara");
        licensee.put(0xA9, "technos japan");
        licensee.put(0xAA, "broderbund");
        licensee.put(0xAC, "Toei animation");
        licensee.put(0xAD, "toho");
        licensee.put(0xAF, "Namco");
        licensee.put(0xB0, "Acclaim");
        licensee.put(0xB1, "ascii or nexoft");
        licensee.put(0xB2, "Bandai");
        licensee.put(0xB4, "Enix");
        licensee.put(0xB6, "HAL");
        licensee.put(0xB7, "SNK");
        licensee.put(0xB9, "pony canyon");
        licensee.put(0xBA, "*culture brain o");
        licensee.put(0xBB, "Sunsoft");
        licensee.put(0xBD, "Sony imagesoft");
        licensee.put(0xBF, "sammy");
        licensee.put(0xC0, "Taito");
        licensee.put(0xC2, "Kemco");
        licensee.put(0xC3, "Squaresoft");
        licensee.put(0xC4, "tokuma shoten intermedia");
        licensee.put(0xC5, "data east");
        licensee.put(0xC6, "tonkin house");
        licensee.put(0xC8, "koei");
        licensee.put(0xC9, "ufl");
        licensee.put(0xCA, "ultra");
        licensee.put(0xCB, "vap");
        licensee.put(0xCC, "use");
        licensee.put(0xCD, "meldac");
        licensee.put(0xCE, "*pony canyon or");
        licensee.put(0xCF, "angel");
        licensee.put(0xD0, "Taito");
        licensee.put(0xD1, "sofel");
        licensee.put(0xD2, "quest");
        licensee.put(0xD3, "sigma enterprises");
        licensee.put(0xD4, "ask kodansha");
        licensee.put(0xD6, "naxat soft");
        licensee.put(0xD7, "copya systems");
        licensee.put(0xD9, "Banpresto");
        licensee.put(0xDA, "tomy");
        licensee.put(0xDB, "ljn");
        licensee.put(0xDD, "ncs");
        licensee.put(0xDE, "human");
        licensee.put(0xDF, "altron");
        licensee.put(0xE0, "jaleco");
        licensee.put(0xE1, "towachiki");
        licensee.put(0xE2, "uutaka");
        licensee.put(0xE3, "varie");
        licensee.put(0xE5, "epoch");
        licensee.put(0xE7, "athena");
        licensee.put(0xE8, "asmik");
        licensee.put(0xE9, "natsume");
        licensee.put(0xEA, "king records");
        licensee.put(0xEB, "atlus");
        licensee.put(0xEC, "Epic/Sony records");
        licensee.put(0xEE, "igs");
        licensee.put(0xF0, "a wave");
        licensee.put(0xF3, "extreme entertainment");
        licensee.put(0xFF, "ljn");

        licensee.put(0x3300, "none");
        licensee.put(0x3301, "Nintendo R&D1");
        licensee.put(0x3308, "Capcom");
        licensee.put(0x3313, "Electronic Arts");
        licensee.put(0x3318, "Hudson Soft");
        licensee.put(0x3319, "b-ai");
        licensee.put(0x3320, "kss");
        licensee.put(0x3322, "pow");
        licensee.put(0x3324, "PCM Complete");
        licensee.put(0x3325, "san-x");
        licensee.put(0x3328, "Kemco Japan");
        licensee.put(0x3329, "seta");
        licensee.put(0x3330, "Viacom");
        licensee.put(0x3331, "Nintendo");
        licensee.put(0x3332, "Bandai");
        licensee.put(0x3333, "Ocean/Acclaim");
        licensee.put(0x3334, "Konami");
        licensee.put(0x3335, "Hector");
        licensee.put(0x3337, "Taito");
        licensee.put(0x3338, "Hudson");
        licensee.put(0x3339, "Banpresto");
        licensee.put(0x3341, "Ubi Soft");
        licensee.put(0x3342, "Atlus");
        licensee.put(0x3344, "Malibu");
        licensee.put(0x3346, "angel");
        licensee.put(0x3347, "Bullet-Proof");
        licensee.put(0x3349, "irem");
        licensee.put(0x3350, "Absolute");
        licensee.put(0x3351, "Acclaim");
        licensee.put(0x3352, "Activision");
        licensee.put(0x3353, "American sammy");
        licensee.put(0x3354, "Konami");
        licensee.put(0x3355, "Hi tech entertainment");
        licensee.put(0x3356, "LJN");
        licensee.put(0x3357, "Matchbox");
        licensee.put(0x3358, "Mattel");
        licensee.put(0x3359, "Milton Bradley");
        licensee.put(0x3360, "Titus");
        licensee.put(0x3361, "Virgin");
        licensee.put(0x3364, "LucasArts");
        licensee.put(0x3367, "Ocean");
        licensee.put(0x3369, "Electronic Arts");
        licensee.put(0x3370, "Infogrames");
        licensee.put(0x3371, "Interplay");
        licensee.put(0x3372, "Broderbund");
        licensee.put(0x3373, "sculptured");
        licensee.put(0x3375, "sci");
        licensee.put(0x3378, "THQ");
        licensee.put(0x3379, "Accolade");
        licensee.put(0x3380, "misawa");
        licensee.put(0x3383, "lozc");
        licensee.put(0x3386, "tokuma shoten i*");
        licensee.put(0x3387, "tsukuda ori*");
        licensee.put(0x3391, "Chunsoft");
        licensee.put(0x3392, "Video system");
        licensee.put(0x3393, "Ocean/Acclaim");
        licensee.put(0x3395, "Varie");
        licensee.put(0x3396, "Yonezawa/s'pal");
        licensee.put(0x3397, "Kaneko");
        licensee.put(0x3399, "Pack in soft");
        licensee.put(0x33A4, "Konami (Yu-Gi-Oh!)");

        cartridgeType.put(0x00, "ROM");
        cartridgeType.put(0x01, "MBC1");
        cartridgeType.put(0x02, "MBC1+RAM");
        cartridgeType.put(0x03, "MBC1+RAM+BATTERY");
        cartridgeType.put(0x05, "MBC2");
        cartridgeType.put(0x06, "MBC2+BATTERY");
        cartridgeType.put(0x08, "ROM+RAM");
        cartridgeType.put(0x09, "ROM+RAM+BATTERY");
        cartridgeType.put(0x0B, "MMM01");
        cartridgeType.put(0x0C, "MMM01+RAM");
        cartridgeType.put(0x0D, "MMM01+RAM+BATTERY");
        cartridgeType.put(0x0F, "MBC3+TIMER+BATTERY");
        cartridgeType.put(0x10, "MBC3+TIMER+RAM+BATTERY");
        cartridgeType.put(0x11, "MBC3");
        cartridgeType.put(0x12, "MBC3+RAM");
        cartridgeType.put(0x13, "MBC3+RAM+BATTERY");
        cartridgeType.put(0x15, "MBC4");
        cartridgeType.put(0x16, "MBC4+RAM");
        cartridgeType.put(0x17, "MBC4+RAM+BATTERY");
        cartridgeType.put(0x19, "MBC5");
        cartridgeType.put(0x1A, "MBC5+RAM");
        cartridgeType.put(0x1B, "MBC5+RAM+BATTERY");
        cartridgeType.put(0x1C, "MBC5+RUMBLE");
        cartridgeType.put(0x1D, "MBC5+RUMBLE+RAM");
        cartridgeType.put(0x1E, "MBC5+RUMBLE+RAM+BATTERY");
        cartridgeType.put(0x20, "MBC6");
        cartridgeType.put(0x22, "MBC7+SENSOR+RUMBLE+RAM+BATTERY");
        cartridgeType.put(0xFC, "POCKET CAMERA");
        cartridgeType.put(0xFD, "Bandai TAMA5");
        cartridgeType.put(0xFE, "HuC3");
        cartridgeType.put(0xFF, "HuC1+RAM+BATTERY");

        romSize.put(0x00, "32KByte -> 0 banks");
        romSize.put(0x01, "64KByte -> 4 banks");
        romSize.put(0x02, "128KByte -> 8 banks");
        romSize.put(0x03, "256KByte -> 16 banks");
        romSize.put(0x04, "512KByte -> 32 banks");
        romSize.put(0x05, "1MByte -> 64 banks");
        romSize.put(0x06, "2MByte -> 128 banks");
        romSize.put(0x07, "4MByte -> 256 banks");
        romSize.put(0x08, "8MByte -> 512 banks");
        romSize.put(0x52, "1.1MByte -> 72 banks");
        romSize.put(0x53, "1.2MByte -> 80 banks");
        romSize.put(0x54, "1.5MByte -> 96 banks");

        ramSize.put(0x00, "0k");
        ramSize.put(0x01, "2k");
        ramSize.put(0x02, "8k");
        ramSize.put(0x03, "32k");
    }
}
