package jboy.system;

import java.util.HashMap;

class Instructions extends HashMap<Integer, Instruction> {
    Instructions(CPU cpu) {
        this.put(0x00, new Instruction(0x00, 0, 4, cpu::nop));
        this.put(0x01, new Instruction(0x01, 2, 12, cpu::ld_bc_xx));
        this.put(0x02, new Instruction(0x02, 0, 8, cpu::ld_bcp_a));
        this.put(0x03, new Instruction(0x03, 0, 8, cpu::inc_bc));
        this.put(0x04, new Instruction(0x04, 0, 4, cpu::inc_b));
        this.put(0x05, new Instruction(0x05, 0, 4, cpu::dec_b));
        this.put(0x06, new Instruction(0x06, 1, 8, cpu::ld_b_x));
        this.put(0x07, new Instruction(0x07, 0, 4, cpu::rlca));
        this.put(0x08, new Instruction(0x08, 2, 20, cpu::ld_xxp_sp));
        this.put(0x09, new Instruction(0x09, 0, 8, cpu::add_hl_bc));
        this.put(0x0A, new Instruction(0x0A, 0, 8, cpu::ld_a_bcp));
        this.put(0x0B, new Instruction(0x0B, 0, 8, cpu::dec_bc));
        this.put(0x0C, new Instruction(0x0C, 0, 4, cpu::inc_c));
        this.put(0x0D, new Instruction(0x0D, 0, 4, cpu::dec_c));
        this.put(0x0E, new Instruction(0x0E, 1, 8, cpu::ld_c_x));
        this.put(0x0F, new Instruction(0x0F, 0, 4, cpu::rrca));

        this.put(0x10, new Instruction(0x10, 1, 4, cpu::stop));
        this.put(0x11, new Instruction(0x11, 2, 12, cpu::ld_de_xx));
        this.put(0x12, new Instruction(0x12, 0, 8, cpu::ld_dep_a));
        this.put(0x13, new Instruction(0x13, 0, 8, cpu::inc_de));
        this.put(0x14, new Instruction(0x14, 0, 4, cpu::inc_d));
        this.put(0x15, new Instruction(0x15, 0, 4, cpu::dec_d));
        this.put(0x16, new Instruction(0x16, 1, 8, cpu::ld_d_x));
        this.put(0x17, new Instruction(0x17, 0, 4, cpu::rla));
        this.put(0x18, new Instruction(0x18, 1, 12, cpu::jr_x));
        this.put(0x19, new Instruction(0x19, 0, 8, cpu::add_hl_de));
        this.put(0x1A, new Instruction(0x1A, 0, 8, cpu::ld_a_dep));
        this.put(0x1B, new Instruction(0x1B, 0, 4, cpu::dec_de));
        this.put(0x1C, new Instruction(0x1C, 0, 4, cpu::inc_e));
        this.put(0x1D, new Instruction(0x1D, 0, 4, cpu::dec_e));
        this.put(0x1E, new Instruction(0x1E, 1, 8, cpu::ld_e_x));
//        this.put(0x1F, new Instruction(0x1F, 0, 4, cpu::rra));

//        this.put(0x20, new Instruction(0x20, 1, 1, cpu::jr_nz_x));
//        this.put(0x21, new Instruction(0x21, 2, 1, cpu::ld_hl_xx));
//        this.put(0x22, new Instruction(0x22, 0, 1, cpu::ldi_hlp_a));
//        this.put(0x23, new Instruction(0x23, 0, 1, cpu::inc_hl));
//        this.put(0x24, new Instruction(0x24, 0, 1, cpu::inc_h));
//        this.put(0x25, new Instruction(0x25, 0, 1, cpu::dec_h));
        this.put(0x26, new Instruction(0x26, 1, 1, cpu::ld_h_x));
        this.put(0x27, new Instruction(0x27, 0, 1, cpu::daa));
//        this.put(0x28, new Instruction(0x28, 1, 1, cpu::jr_z_x));
//        this.put(0x29, new Instruction(0x29, 0, 1, cpu::add_hl_hl));
//        this.put(0x2A, new Instruction(0x2A, 0, 1, cpu::ldi_a_hlp));
//        this.put(0x2B, new Instruction(0x2B, 0, 1, cpu::dec_hl));
//        this.put(0x2C, new Instruction(0x2C, 0, 1, cpu::inc_l));
//        this.put(0x2D, new Instruction(0x2D, 0, 1, cpu::dec_l));
        this.put(0x2E, new Instruction(0x2E, 1, 1, cpu::ld_l_x));
//        this.put(0x2F, new Instruction(0x2F, 0, 1, cpu::cpl));

//        this.put(0x30, new Instruction(0x30, 1, 1, cpu::jr_nc_x));
//        this.put(0x31, new Instruction(0x31, 2, 1, cpu::ld_sp_xx));
//        this.put(0x32, new Instruction(0x32, 0, 1, cpu::ldd_hlp_a));
//        this.put(0x33, new Instruction(0x33, 0, 1, cpu::inc_sp));
//        this.put(0x34, new Instruction(0x34, 0, 1, cpu::inc_hlp));
//        this.put(0x35, new Instruction(0x35, 0, 1, cpu::dec_hlp));
//        this.put(0x36, new Instruction(0x36, 1, 1, cpu::ld_hlp_x));
//        this.put(0x37, new Instruction(0x37, 0, 1, cpu::scf));
//        this.put(0x38, new Instruction(0x38, 1, 1, cpu::jr_c_x));
//        this.put(0x39, new Instruction(0x39, 0, 1, cpu::add_hl_sp));
//        this.put(0x3A, new Instruction(0x3A, 0, 1, cpu::ldd_a_hlp));
//        this.put(0x3B, new Instruction(0x3B, 0, 1, cpu::dec_sp));
//        this.put(0x3C, new Instruction(0x3C, 0, 1, cpu::inc_a));
//        this.put(0x3D, new Instruction(0x3D, 0, 1, cpu::dec_a));
        this.put(0x3E, new Instruction(0x3E, 1, 1, cpu::ld_a_x));
//        this.put(0x3F, new Instruction(0x3F, 0, 1, cpu::ccf));

//        this.put(0x40, new Instruction(0x40, 0, 1, cpu::ld_b_b));
//        this.put(0x41, new Instruction(0x41, 0, 1, cpu::ld_b_c));
//        this.put(0x42, new Instruction(0x42, 0, 1, cpu::ld_b_d));
//        this.put(0x43, new Instruction(0x43, 0, 1, cpu::ld_b_e));
//        this.put(0x44, new Instruction(0x44, 0, 1, cpu::ld_b_h));
//        this.put(0x45, new Instruction(0x45, 0, 1, cpu::ld_b_l));
//        this.put(0x46, new Instruction(0x46, 0, 1, cpu::ld_b_hlp));
//        this.put(0x47, new Instruction(0x47, 0, 1, cpu::ld_b_a));
//        this.put(0x48, new Instruction(0x48, 0, 1, cpu::ld_c_b));
//        this.put(0x49, new Instruction(0x49, 0, 1, cpu::ld_c_c));
//        this.put(0x4A, new Instruction(0x4A, 0, 1, cpu::ld_c_d));
//        this.put(0x4B, new Instruction(0x4B, 0, 1, cpu::ld_c_e));
//        this.put(0x4C, new Instruction(0x4C, 0, 1, cpu::ld_c_h));
//        this.put(0x4D, new Instruction(0x4D, 0, 1, cpu::ld_c_l));
//        this.put(0x4E, new Instruction(0x4E, 0, 1, cpu::ld_c_hlp));
//        this.put(0x4F, new Instruction(0x4F, 0, 1, cpu::ld_c_a));

//        this.put(0x50, new Instruction(0x50, 0, 1, cpu::ld_d_b));
//        this.put(0x51, new Instruction(0x51, 0, 1, cpu::ld_d_c));
//        this.put(0x52, new Instruction(0x52, 0, 1, cpu::ld_d_d));
//        this.put(0x53, new Instruction(0x53, 0, 1, cpu::ld_d_e));
//        this.put(0x54, new Instruction(0x54, 0, 1, cpu::ld_d_h));
//        this.put(0x55, new Instruction(0x55, 0, 1, cpu::ld_d_l));
//        this.put(0x56, new Instruction(0x56, 0, 1, cpu::ld_d_hlp));
//        this.put(0x57, new Instruction(0x57, 0, 1, cpu::ld_d_a));
//        this.put(0x58, new Instruction(0x58, 0, 1, cpu::ld_e_b));
//        this.put(0x59, new Instruction(0x59, 0, 1, cpu::ld_e_c));
//        this.put(0x5A, new Instruction(0x5A, 0, 1, cpu::ld_e_d));
//        this.put(0x5B, new Instruction(0x5B, 0, 1, cpu::ld_e_e));
//        this.put(0x5C, new Instruction(0x5C, 0, 1, cpu::ld_e_h));
//        this.put(0x5D, new Instruction(0x5D, 0, 1, cpu::ld_e_l));
//        this.put(0x5E, new Instruction(0x5E, 0, 1, cpu::ld_e_hlp));
//        this.put(0x5F, new Instruction(0x5F, 0, 1, cpu::ld_e_a));

//        this.put(0x60, new Instruction(0x60, 0, 1, cpu::ld_h_b));
//        this.put(0x61, new Instruction(0x61, 0, 1, cpu::ld_h_c));
//        this.put(0x62, new Instruction(0x62, 0, 1, cpu::ld_h_d));
//        this.put(0x63, new Instruction(0x63, 0, 1, cpu::ld_h_e));
//        this.put(0x64, new Instruction(0x64, 0, 1, cpu::ld_h_h));
//        this.put(0x65, new Instruction(0x65, 0, 1, cpu::ld_h_l));
//        this.put(0x66, new Instruction(0x66, 0, 1, cpu::ld_h_hlp));
//        this.put(0x67, new Instruction(0x67, 0, 1, cpu::ld_h_a));
//        this.put(0x68, new Instruction(0x68, 0, 1, cpu::ld_l_b));
//        this.put(0x69, new Instruction(0x69, 0, 1, cpu::ld_l_c));
//        this.put(0x6A, new Instruction(0x6A, 0, 1, cpu::ld_l_d));
//        this.put(0x6B, new Instruction(0x6B, 0, 1, cpu::ld_l_e));
//        this.put(0x6C, new Instruction(0x6C, 0, 1, cpu::ld_l_h));
//        this.put(0x6D, new Instruction(0x6D, 0, 1, cpu::ld_l_l));
//        this.put(0x6E, new Instruction(0x6E, 0, 1, cpu::ld_l_hlp));
//        this.put(0x6F, new Instruction(0x6F, 0, 1, cpu::ld_l_a));

//        this.put(0x70, new Instruction(0x70, 0, 1, cpu::ld_hlp_b));
//        this.put(0x71, new Instruction(0x71, 0, 1, cpu::ld_hlp_c));
//        this.put(0x72, new Instruction(0x72, 0, 1, cpu::ld_hlp_d));
//        this.put(0x73, new Instruction(0x73, 0, 1, cpu::ld_hlp_e));
//        this.put(0x74, new Instruction(0x74, 0, 1, cpu::ld_hlp_h));
//        this.put(0x75, new Instruction(0x75, 0, 1, cpu::ld_hlp_l));
//        this.put(0x76, new Instruction(0x76, 0, 1, cpu::halt));
//        this.put(0x77, new Instruction(0x77, 0, 1, cpu::ld_hlp_a));
//        this.put(0x78, new Instruction(0x78, 0, 1, cpu::ld_a_b));
//        this.put(0x79, new Instruction(0x79, 0, 1, cpu::ld_a_c));
//        this.put(0x7A, new Instruction(0x7A, 0, 1, cpu::ld_a_d));
//        this.put(0x7B, new Instruction(0x7B, 0, 1, cpu::ld_a_e));
//        this.put(0x7C, new Instruction(0x7C, 0, 1, cpu::ld_a_h));
//        this.put(0x7D, new Instruction(0x7D, 0, 1, cpu::ld_a_l));
//        this.put(0x7E, new Instruction(0x7E, 0, 1, cpu::ld_a_hlp));
//        this.put(0x7F, new Instruction(0x7F, 0, 1, cpu::ld_a_a));

//        this.put(0x80, new Instruction(0x80, 0, 1, cpu::add_a_b));
//        this.put(0x81, new Instruction(0x81, 0, 1, cpu::add_a_c));
//        this.put(0x82, new Instruction(0x82, 0, 1, cpu::add_a_d));
//        this.put(0x83, new Instruction(0x83, 0, 1, cpu::add_a_e));
//        this.put(0x84, new Instruction(0x84, 0, 1, cpu::add_a_h));
//        this.put(0x85, new Instruction(0x85, 0, 1, cpu::add_a_l));
//        this.put(0x86, new Instruction(0x86, 0, 1, cpu::add_a_hlp));
//        this.put(0x87, new Instruction(0x87, 0, 1, cpu::add_a_a));
//        this.put(0x88, new Instruction(0x88, 0, 1, cpu::adc_a_b));
//        this.put(0x89, new Instruction(0x89, 0, 1, cpu::adc_a_c));
//        this.put(0x8A, new Instruction(0x8A, 0, 1, cpu::adc_a_d));
//        this.put(0x8B, new Instruction(0x8B, 0, 1, cpu::adc_a_e));
//        this.put(0x8C, new Instruction(0x8C, 0, 1, cpu::adc_a_h));
//        this.put(0x8D, new Instruction(0x8D, 0, 1, cpu::adc_a_l));
//        this.put(0x8E, new Instruction(0x8E, 0, 1, cpu::adc_a_hlp));
//        this.put(0x8F, new Instruction(0x8F, 0, 1, cpu::adc_a_a));

//        this.put(0x90, new Instruction(0x90, 0, 1, cpu::sub_b));
//        this.put(0x91, new Instruction(0x91, 0, 1, cpu::sub_c));
//        this.put(0x92, new Instruction(0x92, 0, 1, cpu::sub_d));
//        this.put(0x93, new Instruction(0x93, 0, 1, cpu::sub_e));
//        this.put(0x94, new Instruction(0x94, 0, 1, cpu::sub_h));
//        this.put(0x95, new Instruction(0x95, 0, 1, cpu::sub_l));
//        this.put(0x96, new Instruction(0x96, 0, 1, cpu::sub_hlp));
//        this.put(0x97, new Instruction(0x97, 0, 1, cpu::sub_a));
//        this.put(0x98, new Instruction(0x98, 0, 1, cpu::sbc_a_b));
//        this.put(0x99, new Instruction(0x99, 0, 1, cpu::sbc_a_c));
//        this.put(0x9A, new Instruction(0x9A, 0, 1, cpu::sbc_a_d));
//        this.put(0x9B, new Instruction(0x9B, 0, 1, cpu::sbc_a_e));
//        this.put(0x9C, new Instruction(0x9C, 0, 1, cpu::sbc_a_h));
//        this.put(0x9D, new Instruction(0x9D, 0, 1, cpu::sbc_a_l));
//        this.put(0x9E, new Instruction(0x9E, 0, 1, cpu::sbc_a_hlp));
//        this.put(0x9F, new Instruction(0x9F, 0, 1, cpu::sbc_a_a));

//        this.put(0xA0, new Instruction(0xA0, 0, 1, cpu::and_b));
//        this.put(0xA1, new Instruction(0xA1, 0, 1, cpu::and_c));
//        this.put(0xA2, new Instruction(0xA2, 0, 1, cpu::and_d));
//        this.put(0xA3, new Instruction(0xA3, 0, 1, cpu::and_e));
//        this.put(0xA4, new Instruction(0xA4, 0, 1, cpu::and_h));
//        this.put(0xA5, new Instruction(0xA5, 0, 1, cpu::and_l));
//        this.put(0xA6, new Instruction(0xA6, 0, 1, cpu::and_hlp));
//        this.put(0xA7, new Instruction(0xA7, 0, 1, cpu::and_a));
//        this.put(0xA8, new Instruction(0xA8, 0, 1, cpu::xor_b));
//        this.put(0xA9, new Instruction(0xA9, 0, 1, cpu::xor_c));
//        this.put(0xAA, new Instruction(0xAA, 0, 1, cpu::xor_d));
//        this.put(0xAB, new Instruction(0xAB, 0, 1, cpu::xor_e));
//        this.put(0xAC, new Instruction(0xAC, 0, 1, cpu::xor_h));
//        this.put(0xAD, new Instruction(0xAD, 0, 1, cpu::xor_l));
//        this.put(0xAE, new Instruction(0xAE, 0, 1, cpu::xor_hlp));
//        this.put(0xAF, new Instruction(0xAF, 0, 1, cpu::xor_a));

//        this.put(0xB0, new Instruction(0xB0, 0, 1, cpu::or_b));
//        this.put(0xB1, new Instruction(0xB1, 0, 1, cpu::or_c));
//        this.put(0xB2, new Instruction(0xB2, 0, 1, cpu::or_d));
//        this.put(0xB3, new Instruction(0xB3, 0, 1, cpu::or_e));
//        this.put(0xB4, new Instruction(0xB4, 0, 1, cpu::or_h));
//        this.put(0xB5, new Instruction(0xB5, 0, 1, cpu::or_l));
//        this.put(0xB6, new Instruction(0xB6, 0, 1, cpu::or_hlp));
//        this.put(0xB7, new Instruction(0xB7, 0, 1, cpu::or_a));
//        this.put(0xB8, new Instruction(0xB8, 0, 1, cpu::cp_b));
//        this.put(0xB9, new Instruction(0xB9, 0, 1, cpu::cp_c));
//        this.put(0xBA, new Instruction(0xBA, 0, 1, cpu::cp_d));
//        this.put(0xBB, new Instruction(0xBB, 0, 1, cpu::cp_e));
//        this.put(0xBC, new Instruction(0xBC, 0, 1, cpu::cp_h));
//        this.put(0xBD, new Instruction(0xBD, 0, 1, cpu::cp_l));
//        this.put(0xBE, new Instruction(0xBE, 0, 1, cpu::cp_hlp));
//        this.put(0xBF, new Instruction(0xBF, 0, 1, cpu::cp_a));

//        this.put(0xC0, new Instruction(0xC0, 0, 1, cpu::ret_nz));
//        this.put(0xC1, new Instruction(0xC1, 0, 1, cpu::pop_bc));
//        this.put(0xC2, new Instruction(0xC2, 2, 1, cpu::jp_nz_xx));
//        this.put(0xC3, new Instruction(0xC3, 2, 1, cpu::jp_xx));
//        this.put(0xC4, new Instruction(0xC4, 2, 1, cpu::call_nz_xx));
//        this.put(0xC5, new Instruction(0xC5, 0, 1, cpu::push_bc));
//        this.put(0xC6, new Instruction(0xC6, 1, 1, cpu::add_a_x));
//        this.put(0xC7, new Instruction(0xC7, 0, 1, cpu::rst_00));
//        this.put(0xC8, new Instruction(0xC8, 0, 1, cpu::ret_z));
//        this.put(0xC9, new Instruction(0xC9, 0, 1, cpu::ret));
//        this.put(0xCA, new Instruction(0xCA, 2, 1, cpu::jp_z_xx));
//        this.put(0xCC, new Instruction(0xCC, 2, 1, cpu::call_z_xx));
//        this.put(0xCD, new Instruction(0xCD, 2, 1, cpu::call_xx));
//        this.put(0xCE, new Instruction(0xCE, 1, 1, cpu::adc_a_x));
//        this.put(0xCF, new Instruction(0xCF, 0, 1, cpu::rst_08));

//        this.put(0xD0, new Instruction(0xD0, 0, 1, cpu::ret_nc));
//        this.put(0xD1, new Instruction(0xD1, 0, 1, cpu::pop_de));
//        this.put(0xD2, new Instruction(0xD2, 2, 1, cpu::jp_nc_xx));
        this.put(0xD3, new Instruction(0xD3, 0, 4, cpu::nop));
//        this.put(0xD4, new Instruction(0xD4, 2, 1, cpu::call_nc_xx));
//        this.put(0xD5, new Instruction(0xD5, 0, 1, cpu::push_de));
//        this.put(0xD6, new Instruction(0xD6, 1, 1, cpu::sub_x));
//        this.put(0xD7, new Instruction(0xD7, 0, 1, cpu::rst_10));
//        this.put(0xD8, new Instruction(0xD8, 0, 1, cpu::ret_c));
//        this.put(0xD9, new Instruction(0xD9, 0, 1, cpu::reti));
//        this.put(0xDA, new Instruction(0xDA, 2, 1, cpu::jp_c_xx));
        this.put(0xDB, new Instruction(0xDB, 0, 4, cpu::nop));
//        this.put(0xDC, new Instruction(0xDC, 2, 1, cpu::call_c_xx));
        this.put(0xDD, new Instruction(0xDD, 0, 4, cpu::nop));
//        this.put(0xDE, new Instruction(0xDE, 1, 1, cpu::sbc_a_x));
//        this.put(0xDF, new Instruction(0xDF, 0, 1, cpu::rst_18));

//        this.put(0xE0, new Instruction(0xE0, 1, 1, cpu::ldh_xp_a));
//        this.put(0xE1, new Instruction(0xE1, 0, 1, cpu::pop_hl));
//        this.put(0xE2, new Instruction(0xE2, 1, 1, cpu::ld_cp_a));
        this.put(0xE3, new Instruction(0xE3, 0, 4, cpu::nop));
        this.put(0xE4, new Instruction(0xE4, 0, 4, cpu::nop));
//        this.put(0xE5, new Instruction(0xE5, 0, 1, cpu::push_hl));
//        this.put(0xE6, new Instruction(0xE6, 1, 1, cpu::and_x));
//        this.put(0xE7, new Instruction(0xE7, 0, 1, cpu::rst_20));
//        this.put(0xE8, new Instruction(0xE8, 1, 1, cpu::add_sp_x));
//        this.put(0xE9, new Instruction(0xE9, 0, 1, cpu::jp_hlp));
//        this.put(0xEA, new Instruction(0xEA, 2, 1, cpu::ld_xxp_a));
        this.put(0xEB, new Instruction(0xEB, 0, 4, cpu::nop));
        this.put(0xEC, new Instruction(0xEC, 0, 4, cpu::nop));
        this.put(0xED, new Instruction(0xED, 0, 4, cpu::nop));
//        this.put(0xEE, new Instruction(0xEE, 1, 1, cpu::xor_x));
//        this.put(0xEF, new Instruction(0xEF, 0, 1, cpu::rst_28));

//        this.put(0xF0, new Instruction(0xF0, 1, 1, cpu::ldh_a_xp));
//        this.put(0xF1, new Instruction(0xF1, 0, 1, cpu::pop_af));
//        this.put(0xF2, new Instruction(0xF2, 1, 1, cpu::ld_a_cp));
//        this.put(0xF3, new Instruction(0xF3, 0, 1, cpu::di));
        this.put(0xF4, new Instruction(0xF4, 0, 4, cpu::nop));
//        this.put(0xF5, new Instruction(0xF5, 0, 1, cpu::push_af));
//        this.put(0xF6, new Instruction(0xF6, 1, 1, cpu::or_x));
//        this.put(0xF7, new Instruction(0xF7, 0, 1, cpu::rst_30));
//        this.put(0xF8, new Instruction(0xF8, 1, 1, cpu::ld_hl_sp_x));
//        this.put(0xF9, new Instruction(0xF9, 0, 1, cpu::ld_sp_hl));
//        this.put(0xFA, new Instruction(0xFA, 2, 1, cpu::ld_a_xxp));
//        this.put(0xFB, new Instruction(0xFB, 0, 1, cpu::ei));
        this.put(0xFC, new Instruction(0xFC, 0, 4, cpu::nop));
        this.put(0xFD, new Instruction(0xFD, 0, 4, cpu::nop));
//        this.put(0xFE, new Instruction(0xFE, 1, 1, cpu::cp_x));
//        this.put(0xFF, new Instruction(0xFF, 0, 1, cpu::rst_38));

//        this.put(0xCB00, new Instruction(0xCB00, 1, 1, cpu::rlc_b));
//        this.put(0xCB01, new Instruction(0xCB01, 1, 1, cpu::rlc_c));
//        this.put(0xCB02, new Instruction(0xCB02, 1, 1, cpu::rlc_d));
//        this.put(0xCB03, new Instruction(0xCB03, 1, 1, cpu::rlc_e));
//        this.put(0xCB04, new Instruction(0xCB04, 1, 1, cpu::rlc_h));
//        this.put(0xCB05, new Instruction(0xCB05, 1, 1, cpu::rlc_l));
//        this.put(0xCB06, new Instruction(0xCB06, 1, 1, cpu::rlc_hlp));
//        this.put(0xCB07, new Instruction(0xCB07, 1, 1, cpu::rlc_a));
//        this.put(0xCB08, new Instruction(0xCB08, 1, 1, cpu::rrc_b));
//        this.put(0xCB09, new Instruction(0xCB09, 1, 1, cpu::rrc_c));
//        this.put(0xCB0A, new Instruction(0xCB0A, 1, 1, cpu::rrc_d));
//        this.put(0xCB0B, new Instruction(0xCB0B, 1, 1, cpu::rrc_e));
//        this.put(0xCB0C, new Instruction(0xCB0C, 1, 1, cpu::rrc_h));
//        this.put(0xCB0D, new Instruction(0xCB0D, 1, 1, cpu::rrc_l));
//        this.put(0xCB0E, new Instruction(0xCB0E, 1, 1, cpu::rrc_hlp));
//        this.put(0xCB0F, new Instruction(0xCB0F, 1, 1, cpu::rrc_a));

//        this.put(0xCB10, new Instruction(0xCB10, 1, 1, cpu::rl_b));
//        this.put(0xCB11, new Instruction(0xCB11, 1, 1, cpu::rl_c));
//        this.put(0xCB12, new Instruction(0xCB12, 1, 1, cpu::rl_d));
//        this.put(0xCB13, new Instruction(0xCB13, 1, 1, cpu::rl_e));
//        this.put(0xCB14, new Instruction(0xCB14, 1, 1, cpu::rl_h));
//        this.put(0xCB15, new Instruction(0xCB15, 1, 1, cpu::rl_l));
//        this.put(0xCB16, new Instruction(0xCB16, 1, 1, cpu::rl_hlp));
//        this.put(0xCB17, new Instruction(0xCB17, 1, 1, cpu::rl_a));
//        this.put(0xCB18, new Instruction(0xCB18, 1, 1, cpu::rr_b));
//        this.put(0xCB19, new Instruction(0xCB19, 1, 1, cpu::rr_c));
//        this.put(0xCB1A, new Instruction(0xCB1A, 1, 1, cpu::rr_d));
//        this.put(0xCB1B, new Instruction(0xCB1B, 1, 1, cpu::rr_e));
//        this.put(0xCB1C, new Instruction(0xCB1C, 1, 1, cpu::rr_h));
//        this.put(0xCB1D, new Instruction(0xCB1D, 1, 1, cpu::rr_l));
//        this.put(0xCB1E, new Instruction(0xCB1E, 1, 1, cpu::rr_hlp));
//        this.put(0xCB1F, new Instruction(0xCB1F, 1, 1, cpu::rr_a));

//        this.put(0xCB20, new Instruction(0xCB20, 1, 1, cpu::sla_b));
//        this.put(0xCB21, new Instruction(0xCB21, 1, 1, cpu::sla_c));
//        this.put(0xCB22, new Instruction(0xCB22, 1, 1, cpu::sla_d));
//        this.put(0xCB23, new Instruction(0xCB23, 1, 1, cpu::sla_e));
//        this.put(0xCB24, new Instruction(0xCB24, 1, 1, cpu::sla_h));
//        this.put(0xCB25, new Instruction(0xCB25, 1, 1, cpu::sla_l));
//        this.put(0xCB26, new Instruction(0xCB26, 1, 1, cpu::sla_hlp));
//        this.put(0xCB27, new Instruction(0xCB27, 1, 1, cpu::sla_a));
//        this.put(0xCB28, new Instruction(0xCB28, 1, 1, cpu::sra_b));
//        this.put(0xCB29, new Instruction(0xCB29, 1, 1, cpu::sra_c));
//        this.put(0xCB2A, new Instruction(0xCB2A, 1, 1, cpu::sra_d));
//        this.put(0xCB2B, new Instruction(0xCB2B, 1, 1, cpu::sra_e));
//        this.put(0xCB2C, new Instruction(0xCB2C, 1, 1, cpu::sra_h));
//        this.put(0xCB2D, new Instruction(0xCB2D, 1, 1, cpu::sra_l));
//        this.put(0xCB2E, new Instruction(0xCB2E, 1, 1, cpu::sra_hlp));
//        this.put(0xCB2F, new Instruction(0xCB2F, 1, 1, cpu::sra_a));

//        this.put(0xCB30, new Instruction(0xCB30, 1, 1, cpu::swap_b));
//        this.put(0xCB31, new Instruction(0xCB31, 1, 1, cpu::swap_c));
//        this.put(0xCB32, new Instruction(0xCB32, 1, 1, cpu::swap_d));
//        this.put(0xCB33, new Instruction(0xCB33, 1, 1, cpu::swap_e));
//        this.put(0xCB34, new Instruction(0xCB34, 1, 1, cpu::swap_h));
//        this.put(0xCB35, new Instruction(0xCB35, 1, 1, cpu::swap_l));
//        this.put(0xCB36, new Instruction(0xCB36, 1, 1, cpu::swap_hlp));
//        this.put(0xCB37, new Instruction(0xCB37, 1, 1, cpu::swap_a));
//        this.put(0xCB38, new Instruction(0xCB38, 1, 1, cpu::srl_b));
//        this.put(0xCB39, new Instruction(0xCB39, 1, 1, cpu::srl_c));
//        this.put(0xCB3A, new Instruction(0xCB3A, 1, 1, cpu::srl_d));
//        this.put(0xCB3B, new Instruction(0xCB3B, 1, 1, cpu::srl_e));
//        this.put(0xCB3C, new Instruction(0xCB3C, 1, 1, cpu::srl_h));
//        this.put(0xCB3D, new Instruction(0xCB3D, 1, 1, cpu::srl_l));
//        this.put(0xCB3E, new Instruction(0xCB3E, 1, 1, cpu::srl_hlp));
//        this.put(0xCB3F, new Instruction(0xCB3F, 1, 1, cpu::srl_a));

//        this.put(0xCB40, new Instruction(0xCB40, 1, 1, cpu::bit_0_b));
//        this.put(0xCB41, new Instruction(0xCB41, 1, 1, cpu::bit_0_c));
//        this.put(0xCB42, new Instruction(0xCB42, 1, 1, cpu::bit_0_d));
//        this.put(0xCB43, new Instruction(0xCB43, 1, 1, cpu::bit_0_e));
//        this.put(0xCB44, new Instruction(0xCB44, 1, 1, cpu::bit_0_h));
//        this.put(0xCB45, new Instruction(0xCB45, 1, 1, cpu::bit_0_l));
//        this.put(0xCB46, new Instruction(0xCB46, 1, 1, cpu::bit_0_hlp));
//        this.put(0xCB47, new Instruction(0xCB47, 1, 1, cpu::bit_0_a));
//        this.put(0xCB48, new Instruction(0xCB48, 1, 1, cpu::bit_1_b));
//        this.put(0xCB49, new Instruction(0xCB49, 1, 1, cpu::bit_1_c));
//        this.put(0xCB4A, new Instruction(0xCB4A, 1, 1, cpu::bit_1_d));
//        this.put(0xCB4B, new Instruction(0xCB4B, 1, 1, cpu::bit_1_e));
//        this.put(0xCB4C, new Instruction(0xCB4C, 1, 1, cpu::bit_1_h));
//        this.put(0xCB4D, new Instruction(0xCB4D, 1, 1, cpu::bit_1_l));
//        this.put(0xCB4E, new Instruction(0xCB4E, 1, 1, cpu::bit_1_hlp));
//        this.put(0xCB4F, new Instruction(0xCB4F, 1, 1, cpu::bit_1_a));

//        this.put(0xCB50, new Instruction(0xCB50, 1, 1, cpu::bit_2_b));
//        this.put(0xCB51, new Instruction(0xCB51, 1, 1, cpu::bit_2_c));
//        this.put(0xCB52, new Instruction(0xCB52, 1, 1, cpu::bit_2_d));
//        this.put(0xCB53, new Instruction(0xCB53, 1, 1, cpu::bit_2_e));
//        this.put(0xCB54, new Instruction(0xCB54, 1, 1, cpu::bit_2_h));
//        this.put(0xCB55, new Instruction(0xCB55, 1, 1, cpu::bit_2_l));
//        this.put(0xCB56, new Instruction(0xCB56, 1, 1, cpu::bit_2_hlp));
//        this.put(0xCB57, new Instruction(0xCB57, 1, 1, cpu::bit_2_a));
//        this.put(0xCB58, new Instruction(0xCB58, 1, 1, cpu::bit_3_b));
//        this.put(0xCB59, new Instruction(0xCB59, 1, 1, cpu::bit_3_c));
//        this.put(0xCB5A, new Instruction(0xCB5A, 1, 1, cpu::bit_3_d));
//        this.put(0xCB5B, new Instruction(0xCB5B, 1, 1, cpu::bit_3_e));
//        this.put(0xCB5C, new Instruction(0xCB5C, 1, 1, cpu::bit_3_h));
//        this.put(0xCB5D, new Instruction(0xCB5D, 1, 1, cpu::bit_3_l));
//        this.put(0xCB5E, new Instruction(0xCB5E, 1, 1, cpu::bit_3_hlp));
//        this.put(0xCB5F, new Instruction(0xCB5F, 1, 1, cpu::bit_3_a));

//        this.put(0xCB60, new Instruction(0xCB60, 1, 1, cpu::bit_4_b));
//        this.put(0xCB61, new Instruction(0xCB61, 1, 1, cpu::bit_4_c));
//        this.put(0xCB62, new Instruction(0xCB62, 1, 1, cpu::bit_4_d));
//        this.put(0xCB63, new Instruction(0xCB63, 1, 1, cpu::bit_4_e));
//        this.put(0xCB64, new Instruction(0xCB64, 1, 1, cpu::bit_4_h));
//        this.put(0xCB65, new Instruction(0xCB65, 1, 1, cpu::bit_4_l));
//        this.put(0xCB66, new Instruction(0xCB66, 1, 1, cpu::bit_4_hlp));
//        this.put(0xCB67, new Instruction(0xCB67, 1, 1, cpu::bit_4_a));
//        this.put(0xCB68, new Instruction(0xCB68, 1, 1, cpu::bit_5_b));
//        this.put(0xCB69, new Instruction(0xCB69, 1, 1, cpu::bit_5_c));
//        this.put(0xCB6A, new Instruction(0xCB6A, 1, 1, cpu::bit_5_d));
//        this.put(0xCB6B, new Instruction(0xCB6B, 1, 1, cpu::bit_5_e));
//        this.put(0xCB6C, new Instruction(0xCB6C, 1, 1, cpu::bit_5_h));
//        this.put(0xCB6D, new Instruction(0xCB6D, 1, 1, cpu::bit_5_l));
//        this.put(0xCB6E, new Instruction(0xCB6E, 1, 1, cpu::bit_5_hlp));
//        this.put(0xCB6F, new Instruction(0xCB6F, 1, 1, cpu::bit_5_a));

//        this.put(0xCB70, new Instruction(0xCB70, 1, 1, cpu::bit_6_b));
//        this.put(0xCB71, new Instruction(0xCB71, 1, 1, cpu::bit_6_c));
//        this.put(0xCB72, new Instruction(0xCB72, 1, 1, cpu::bit_6_d));
//        this.put(0xCB73, new Instruction(0xCB73, 1, 1, cpu::bit_6_e));
//        this.put(0xCB74, new Instruction(0xCB74, 1, 1, cpu::bit_6_h));
//        this.put(0xCB75, new Instruction(0xCB75, 1, 1, cpu::bit_6_l));
//        this.put(0xCB76, new Instruction(0xCB76, 1, 1, cpu::bit_6_hlp));
//        this.put(0xCB77, new Instruction(0xCB77, 1, 1, cpu::bit_6_a));
//        this.put(0xCB78, new Instruction(0xCB78, 1, 1, cpu::bit_7_b));
//        this.put(0xCB79, new Instruction(0xCB79, 1, 1, cpu::bit_7_c));
//        this.put(0xCB7A, new Instruction(0xCB7A, 1, 1, cpu::bit_7_d));
//        this.put(0xCB7B, new Instruction(0xCB7B, 1, 1, cpu::bit_7_e));
//        this.put(0xCB7C, new Instruction(0xCB7C, 1, 1, cpu::bit_7_h));
//        this.put(0xCB7D, new Instruction(0xCB7D, 1, 1, cpu::bit_7_l));
//        this.put(0xCB7E, new Instruction(0xCB7E, 1, 1, cpu::bit_7_hlp));
//        this.put(0xCB7F, new Instruction(0xCB7F, 1, 1, cpu::bit_7_a));

//        this.put(0xCB80, new Instruction(0xCB80, 1, 1, cpu::res_0_b));
//        this.put(0xCB81, new Instruction(0xCB81, 1, 1, cpu::res_0_c));
//        this.put(0xCB82, new Instruction(0xCB82, 1, 1, cpu::res_0_d));
//        this.put(0xCB83, new Instruction(0xCB83, 1, 1, cpu::res_0_e));
//        this.put(0xCB84, new Instruction(0xCB84, 1, 1, cpu::res_0_h));
//        this.put(0xCB85, new Instruction(0xCB85, 1, 1, cpu::res_0_l));
//        this.put(0xCB86, new Instruction(0xCB86, 1, 1, cpu::res_0_hlp));
//        this.put(0xCB87, new Instruction(0xCB87, 1, 1, cpu::res_0_a));
//        this.put(0xCB88, new Instruction(0xCB88, 1, 1, cpu::res_1_b));
//        this.put(0xCB89, new Instruction(0xCB89, 1, 1, cpu::res_1_c));
//        this.put(0xCB8A, new Instruction(0xCB8A, 1, 1, cpu::res_1_d));
//        this.put(0xCB8B, new Instruction(0xCB8B, 1, 1, cpu::res_1_e));
//        this.put(0xCB8C, new Instruction(0xCB8C, 1, 1, cpu::res_1_h));
//        this.put(0xCB8D, new Instruction(0xCB8D, 1, 1, cpu::res_1_l));
//        this.put(0xCB8E, new Instruction(0xCB8E, 1, 1, cpu::res_1_hlp));
//        this.put(0xCB8F, new Instruction(0xCB8F, 1, 1, cpu::res_1_a));

//        this.put(0xCB90, new Instruction(0xCB90, 1, 1, cpu::res_2_b));
//        this.put(0xCB91, new Instruction(0xCB91, 1, 1, cpu::res_2_c));
//        this.put(0xCB92, new Instruction(0xCB92, 1, 1, cpu::res_2_d));
//        this.put(0xCB93, new Instruction(0xCB93, 1, 1, cpu::res_2_e));
//        this.put(0xCB94, new Instruction(0xCB94, 1, 1, cpu::res_2_h));
//        this.put(0xCB95, new Instruction(0xCB95, 1, 1, cpu::res_2_l));
//        this.put(0xCB96, new Instruction(0xCB96, 1, 1, cpu::res_2_hlp));
//        this.put(0xCB97, new Instruction(0xCB97, 1, 1, cpu::res_2_a));
//        this.put(0xCB98, new Instruction(0xCB98, 1, 1, cpu::res_3_b));
//        this.put(0xCB99, new Instruction(0xCB99, 1, 1, cpu::res_3_c));
//        this.put(0xCB9A, new Instruction(0xCB9A, 1, 1, cpu::res_3_d));
//        this.put(0xCB9B, new Instruction(0xCB9B, 1, 1, cpu::res_3_e));
//        this.put(0xCB9C, new Instruction(0xCB9C, 1, 1, cpu::res_3_h));
//        this.put(0xCB9D, new Instruction(0xCB9D, 1, 1, cpu::res_3_l));
//        this.put(0xCB9E, new Instruction(0xCB9E, 1, 1, cpu::res_3_hlp));
//        this.put(0xCB9F, new Instruction(0xCB9F, 1, 1, cpu::res_3_a));

//        this.put(0xCBA0, new Instruction(0xCBA0, 1, 1, cpu::res_4_b));
//        this.put(0xCBA1, new Instruction(0xCBA1, 1, 1, cpu::res_4_c));
//        this.put(0xCBA2, new Instruction(0xCBA2, 1, 1, cpu::res_4_d));
//        this.put(0xCBA3, new Instruction(0xCBA3, 1, 1, cpu::res_4_e));
//        this.put(0xCBA4, new Instruction(0xCBA4, 1, 1, cpu::res_4_h));
//        this.put(0xCBA5, new Instruction(0xCBA5, 1, 1, cpu::res_4_l));
//        this.put(0xCBA6, new Instruction(0xCBA6, 1, 1, cpu::res_4_hlp));
//        this.put(0xCBA7, new Instruction(0xCBA7, 1, 1, cpu::res_4_a));
//        this.put(0xCBA8, new Instruction(0xCBA8, 1, 1, cpu::res_5_b));
//        this.put(0xCBA9, new Instruction(0xCBA9, 1, 1, cpu::res_5_c));
//        this.put(0xCBAA, new Instruction(0xCBAA, 1, 1, cpu::res_5_d));
//        this.put(0xCBAB, new Instruction(0xCBAB, 1, 1, cpu::res_5_e));
//        this.put(0xCBAC, new Instruction(0xCBAC, 1, 1, cpu::res_5_h));
//        this.put(0xCBAD, new Instruction(0xCBAD, 1, 1, cpu::res_5_l));
//        this.put(0xCBAE, new Instruction(0xCBAE, 1, 1, cpu::res_5_hlp));
//        this.put(0xCBAF, new Instruction(0xCBAF, 1, 1, cpu::res_5_a));

//        this.put(0xCBB0, new Instruction(0xCBB0, 1, 1, cpu::res_6_b));
//        this.put(0xCBB1, new Instruction(0xCBB1, 1, 1, cpu::res_6_c));
//        this.put(0xCBB2, new Instruction(0xCBB2, 1, 1, cpu::res_6_d));
//        this.put(0xCBB3, new Instruction(0xCBB3, 1, 1, cpu::res_6_e));
//        this.put(0xCBB4, new Instruction(0xCBB4, 1, 1, cpu::res_6_h));
//        this.put(0xCBB5, new Instruction(0xCBB5, 1, 1, cpu::res_6_l));
//        this.put(0xCBB6, new Instruction(0xCBB6, 1, 1, cpu::res_6_hlp));
//        this.put(0xCBB7, new Instruction(0xCBB7, 1, 1, cpu::res_6_a));
//        this.put(0xCBB8, new Instruction(0xCBB8, 1, 1, cpu::res_7_b));
//        this.put(0xCBB9, new Instruction(0xCBB9, 1, 1, cpu::res_7_c));
//        this.put(0xCBBA, new Instruction(0xCBBA, 1, 1, cpu::res_7_d));
//        this.put(0xCBBB, new Instruction(0xCBBB, 1, 1, cpu::res_7_e));
//        this.put(0xCBBC, new Instruction(0xCBBC, 1, 1, cpu::res_7_h));
//        this.put(0xCBBD, new Instruction(0xCBBD, 1, 1, cpu::res_7_l));
//        this.put(0xCBBE, new Instruction(0xCBBE, 1, 1, cpu::res_7_hlp));
//        this.put(0xCBBF, new Instruction(0xCBBF, 1, 1, cpu::res_7_a));

//        this.put(0xCBC0, new Instruction(0xCBC0, 1, 1, cpu::set_0_b));
//        this.put(0xCBC1, new Instruction(0xCBC1, 1, 1, cpu::set_0_c));
//        this.put(0xCBC2, new Instruction(0xCBC2, 1, 1, cpu::set_0_d));
//        this.put(0xCBC3, new Instruction(0xCBC3, 1, 1, cpu::set_0_e));
//        this.put(0xCBC4, new Instruction(0xCBC4, 1, 1, cpu::set_0_h));
//        this.put(0xCBC5, new Instruction(0xCBC5, 1, 1, cpu::set_0_l));
//        this.put(0xCBC6, new Instruction(0xCBC6, 1, 1, cpu::set_0_hlp));
//        this.put(0xCBC7, new Instruction(0xCBC7, 1, 1, cpu::set_0_a));
//        this.put(0xCBC8, new Instruction(0xCBC8, 1, 1, cpu::set_1_b));
//        this.put(0xCBC9, new Instruction(0xCBC9, 1, 1, cpu::set_1_c));
//        this.put(0xCBCA, new Instruction(0xCBCA, 1, 1, cpu::set_1_d));
//        this.put(0xCBCB, new Instruction(0xCBCB, 1, 1, cpu::set_1_e));
//        this.put(0xCBCC, new Instruction(0xCBCC, 1, 1, cpu::set_1_h));
//        this.put(0xCBCD, new Instruction(0xCBCD, 1, 1, cpu::set_1_l));
//        this.put(0xCBCE, new Instruction(0xCBCE, 1, 1, cpu::set_1_hlp));
//        this.put(0xCBCF, new Instruction(0xCBCF, 1, 1, cpu::set_1_a));

//        this.put(0xCBD0, new Instruction(0xCBD0, 1, 1, cpu::set_2_b));
//        this.put(0xCBD1, new Instruction(0xCBD1, 1, 1, cpu::set_2_c));
//        this.put(0xCBD2, new Instruction(0xCBD2, 1, 1, cpu::set_2_d));
//        this.put(0xCBD3, new Instruction(0xCBD3, 1, 1, cpu::set_2_e));
//        this.put(0xCBD4, new Instruction(0xCBD4, 1, 1, cpu::set_2_h));
//        this.put(0xCBD5, new Instruction(0xCBD5, 1, 1, cpu::set_2_l));
//        this.put(0xCBD6, new Instruction(0xCBD6, 1, 1, cpu::set_2_hlp));
//        this.put(0xCBD7, new Instruction(0xCBD7, 1, 1, cpu::set_2_a));
//        this.put(0xCBD8, new Instruction(0xCBD8, 1, 1, cpu::set_3_b));
//        this.put(0xCBD9, new Instruction(0xCBD9, 1, 1, cpu::set_3_c));
//        this.put(0xCBDA, new Instruction(0xCBDA, 1, 1, cpu::set_3_d));
//        this.put(0xCBDB, new Instruction(0xCBDB, 1, 1, cpu::set_3_e));
//        this.put(0xCBDC, new Instruction(0xCBDC, 1, 1, cpu::set_3_h));
//        this.put(0xCBDD, new Instruction(0xCBDD, 1, 1, cpu::set_3_l));
//        this.put(0xCBDE, new Instruction(0xCBDE, 1, 1, cpu::set_3_hlp));
//        this.put(0xCBDF, new Instruction(0xCBDF, 1, 1, cpu::set_3_a));

//        this.put(0xCBE0, new Instruction(0xCBE0, 1, 1, cpu::set_4_b));
//        this.put(0xCBE1, new Instruction(0xCBE1, 1, 1, cpu::set_4_c));
//        this.put(0xCBE2, new Instruction(0xCBE2, 1, 1, cpu::set_4_d));
//        this.put(0xCBE3, new Instruction(0xCBE3, 1, 1, cpu::set_4_e));
//        this.put(0xCBE4, new Instruction(0xCBE4, 1, 1, cpu::set_4_h));
//        this.put(0xCBE5, new Instruction(0xCBE5, 1, 1, cpu::set_4_l));
//        this.put(0xCBE6, new Instruction(0xCBE6, 1, 1, cpu::set_4_hlp));
//        this.put(0xCBE7, new Instruction(0xCBE7, 1, 1, cpu::set_4_a));
//        this.put(0xCBE8, new Instruction(0xCBE8, 1, 1, cpu::set_5_b));
//        this.put(0xCBE9, new Instruction(0xCBE9, 1, 1, cpu::set_5_c));
//        this.put(0xCBEA, new Instruction(0xCBEA, 1, 1, cpu::set_5_d));
//        this.put(0xCBEB, new Instruction(0xCBEB, 1, 1, cpu::set_5_e));
//        this.put(0xCBEC, new Instruction(0xCBEC, 1, 1, cpu::set_5_h));
//        this.put(0xCBED, new Instruction(0xCBED, 1, 1, cpu::set_5_l));
//        this.put(0xCBEE, new Instruction(0xCBEE, 1, 1, cpu::set_5_hlp));
//        this.put(0xCBEF, new Instruction(0xCBEF, 1, 1, cpu::set_5_a));

//        this.put(0xCBF0, new Instruction(0xCBF0, 1, 1, cpu::set_6_b));
//        this.put(0xCBF1, new Instruction(0xCBF1, 1, 1, cpu::set_6_c));
//        this.put(0xCBF2, new Instruction(0xCBF2, 1, 1, cpu::set_6_d));
//        this.put(0xCBF3, new Instruction(0xCBF3, 1, 1, cpu::set_6_e));
//        this.put(0xCBF4, new Instruction(0xCBF4, 1, 1, cpu::set_6_h));
//        this.put(0xCBF5, new Instruction(0xCBF5, 1, 1, cpu::set_6_l));
//        this.put(0xCBF6, new Instruction(0xCBF6, 1, 1, cpu::set_6_hlp));
//        this.put(0xCBF7, new Instruction(0xCBF7, 1, 1, cpu::set_6_a));
//        this.put(0xCBF8, new Instruction(0xCBF8, 1, 1, cpu::set_7_b));
//        this.put(0xCBF9, new Instruction(0xCBF9, 1, 1, cpu::set_7_c));
//        this.put(0xCBFA, new Instruction(0xCBFA, 1, 1, cpu::set_7_d));
//        this.put(0xCBFB, new Instruction(0xCBFB, 1, 1, cpu::set_7_e));
//        this.put(0xCBFC, new Instruction(0xCBFC, 1, 1, cpu::set_7_h));
//        this.put(0xCBFD, new Instruction(0xCBFD, 1, 1, cpu::set_7_l));
//        this.put(0xCBFE, new Instruction(0xCBFE, 1, 1, cpu::set_7_hlp));
//        this.put(0xCBFF, new Instruction(0xCBFF, 1, 1, cpu::set_7_a));
    }
}
